#!/usr/bin/env bash
#
# HISTORICAL RECORD of the 2026-08 same-host account-rename migration; the flow
# it drove is complete. Kept for reference — not meant to be run again.
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# STAGES — macOS account cutover after the development layout is already in
# ~/dev. This wizard intentionally has prepare and finish phases because logout
# terminates the first run.
# ──────────────────────────────────────────────────────────────────────────

PHASE="${1:-prepare}"

if [[ "$PHASE" == "prepare" ]]; then
  TOTAL_STAGES=3
  TOTAL_MINUTES=15
  banner "Claude0 macOS account cutover — prepare"

  stage "Confirm staged layout" 3
  step "Confirm ~/dev/claude0 exists and ~/Documents/claude0 does not."
  step "Confirm the VM already reports marcel, /Users/marcel, and a green doctor."
  warn "A full backup is still recommended. Continuing without one accepts possible data loss."
  pause "The staged Mac layout and completed VM migration are confirmed?"

  stage "Test the recovery administrator" 5
  open_url "https://support.apple.com/en-us/102547"
  step "Restart and select Migration Admin at the first login screen."
  step "Confirm its desktop loads, then log out and return to throxy."
  warn "Do not remove Migration Admin until the renamed Mac passes verification."
  pause "The recovery administrator can log in and unlock the Mac?"

  stage "Preflight and rename the Mac account" 7
  step "Generate a fresh home-only manifest and confirm zero BLOCKER lines:"
  note "cd /Users/throxy/dev/claude0"
  note "bun run scripts/migrate-dev-layout.ts preflight --target-home /Users/marcel --source-root /Users/throxy/dev --target-root /Users/marcel/dev"
  step "Finish active Claude work, then stop Claude0/tmux and quit editors/terminals using this account."
  step "Log out of throxy and log into the temporary administrator."
  step "Rename /Users/throxy to /Users/marcel, then control-click throxy in Users & Groups → Advanced Options."
  step "Set Account name to marcel and Home directory to /Users/marcel. Do not change the password."
  step "Restart, log into marcel, and run:"
  note "/Users/marcel/dev/claude0/scripts/migrate-dev-layout-wizard.sh finish"
  warn "This prepare process will end when you log out; that is expected."
  finish
elif [[ "$PHASE" == "finish" ]]; then
  TOTAL_STAGES=3
  TOTAL_MINUTES=15
  banner "Claude0 macOS account cutover — finish"

  stage "Verify the renamed Mac account" 4
  step "Confirm: whoami prints marcel and printf '%s\\n' \"$HOME\" prints /Users/marcel."
  step "Confirm the home owner and secure token:"
  note "ls -ld /Users/marcel; sysadminctl -secureTokenStatus marcel"
  warn "If either check is wrong, stop and use the recovery administrator to correct Advanced Options."
  pause "The account name, home, owner, login, and secure token are correct?"

  stage "Repair the renamed home" 6
  step "Apply the latest home-only manifest; repositories stay in ~/dev while absolute paths are repaired:"
  note "cd /Users/marcel/dev/claude0 && bun run scripts/migrate-dev-layout.ts apply"
  step "Reinstall generated Claude0 integration:"
  note "bun install && bun run bin/claude0.ts setup"
  step "Run bun run /Users/marcel/dev/claude0/bin/claude0.ts config, open the printed file, and confirm repositories.roots is [\"~/dev\"]."
  step "Verify: git -C ~/dev/claude0 worktree list; claude0 terminal status; c0"
  pause "The Mac account, paths, Git worktrees, and Claude0 checks pass?"

  stage "Close the recovery window" 5
  step "Restart the Mac once more and confirm marcel can unlock FileVault and log in."
  step "Resume one pre-migration Claude session and confirm its transcript continues."
  step "Only then remove Migration Admin. Keep its home only if it holds recovery data."
  step "Keep ~/.config/claude0/migrations/*-backup until the next normal backup cycle succeeds."
  finish
else
  printf 'Usage: %s [prepare|finish]\\n' "$0" >&2
  exit 2
fi
